sudo: required
language: java
services:
- docker
env:
- CHANGE_MINIKUBE_NONE_USER=true
before_script:
- unset _JAVA_OPTIONS
- cd finish
- sudo mount --make-rshared /
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
- wget https://github.com/kubernetes/minikube/releases/download/v0.28.2/minikube-linux-amd64 -q
  -O minikube
- chmod +x minikube
- sudo ln -s $(pwd)/minikube /usr/local/bin/minikube
- sudo minikube start --vm-driver=none --bootstrapper=localkube
script:
- mvn -q package
- kubectl apply -f kubernetes.yaml
- sleep 120
- kubectl get pods
- echo `minikube ip`
- mvn verify -Ddockerfile.skip=true -Dcluster.ip=`minikube ip`
- kubectl logs $(kubectl get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}'
  | grep name | head -1)
- kubectl logs $(kubectl get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}'
  | grep name | tail -1)
- kubectl logs $(kubectl get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}'
  | grep ping)
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: 2T6s9+UXwxqg2O7Sbgw5B+1zViGNylB40a2H0ks3FR91w9EEQ/ly2A34c9XsRhkug14GNVBptnjxOhi93tga2UlilXcqLfS/LUAFcHJM8y2jNrtSQNOCqypwsoibpXDrqG8zXWJC4IlcHjM2451TuFb4qMCkB8LzGTaJ07RvyAVOxrOcLZk6F/4b70/bWmEd5lk2XDtRP1/YYVVrT6OhEAl/tTg8SL/mnnxrzl4MaL/ACP1ABU54fg0yrWEfsEAtuTlWUYukJbNqXzMHmgjrEKjezkvL1cS2rGrYMEYoc2VPS2zYi5wyX/IHquWYIu7jhm6cAAYca+OFWS8NbLCdo0s4eQsSrzSTQC9ysNkkrfdZFCIa6SctaTszoS8/wiK5thI57nR8XuhA8k2Za1oShOhG4MHjtqhsr75QRRzNJaq4qFaSivqx74SpM3V3r4dgka9A830vkUYKK7LNecr0nRy32SozmBEKS7VEbLJ3JX/66VHvoV8Ycrlu0UUYq5rwBuR5dJEec8FTSWApjtLzslZUll+6RFsoMwToAanbFsp89cU48+6Ky4UkuW0dS6OEoJSH589SkaxVCNkGESpStdJC2yNg8En84KPNrJGz/qgxgqoH2+3OWkT1yb5ZeAhA9qroZt5rLdazV+tU6oPmMveYXal6Y0YCziGLH5wwh6c=
    on_success: never
    on_failure: always
branches:
  only:
  - master
