// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: kubernetes-microprofile-health
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2018-09-27
:page-description: Explore how to configure liveness and readiness probes in your Kubernetes cluster
:page-tags: ['microservices', 'Kubernetes', 'Docker', 'containers', 'kubectl', 'Minikube', 'MicroProfile', 'mpHealth', 'probe']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'istio', 'kubernetes', 'kubernetes-microprofile-config']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Probing microservices with Kubernetes

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to configure liveness and readiness probes in your Kubernetes cluster to automatically restart unhealthy pods and re-route traffic accordingly.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:name-api: http://[hostname]:31000/api/name
:ping-api: http://[hostname]:32000/api/ping
:win: Windows
:mac: Mac
:linux: Linux

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to create a health check endpoint for your microservices that you can configure {kube} to leverage to keep your microservices running smoothly.

{kube} provides liveness and readiness probes that are used to check the health of your containers. These probes can check certain files in your containers, check a TCP socket, or make HTTP requests. MicroProfile Health exposes a health endpoint on your microservices which allows {kube} to probe your microservice via HTTP.

// =================================================================================================
// Prerequisites
// =================================================================================================

include::{common-includes}/kube-prereq.adoc[]


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Starting/Preparing Cluster
// =================================================================================================

include::{common-includes}/kube-start.adoc[]

// ================================================================================================================================
// ================================================================================================================================

== Add health check to ping microservice

There are two applications that you will work with -- `name` and `ping`. `name` displays a greeting and displays its container name. `ping` accepts a hostname as a parameter and returns `pong` if it can successfully make a request to `name`, otherwise the request fails. The `name` microservice already has a health check implemented, so you will implement a health check for `ping`.

The `ping` microservice should only be healthy when `name` is available. To add this check to the `/health` endpoint you will create a class implementing the `HealthCheck` interface.

Create the `PingHealth` class in `ping/src/main/java/io/openliberty/guides/ping/PingHealth.java`:

[source, Java]
----
include::finish/ping/src/main/java/io/openliberty/guides/ping/PingHealth.java[tags=**;]
----

This health check verifies that the `name` microservice is available at `http://name-service:9080/api`. If it is available then it returns an `UP` status. Similarly, if it is unavailable then it returns a `DOWN` status. When the status is `DOWN` the microservice is considered to be unhealthy.

== Configure readiness and liveness probes

Update the `kubernetes.yaml` file to add the readiness and liveness probes for the containers running the `name` and `ping` microservices.

[source, yaml]
----
include::finish/kubernetes.yaml[tags=**;]
----

The readiness probe is configured to poll the `/health` endpoint. If a GET request on the `/health` endpoint has a status code of at least `200` and less than `400` then the pod will be ready, otherwise the pod will not be ready. The `initialDelaySeconds` field defines how long the probe should wait before it starts to poll. This is useful because you can time the readiness and liveness polls such that they do not interfere with each other. For example the liveness probe could kill the pod before it is even in the ready state. The `periodSeconds` option defines how often the probe should poll the given endpoint. The `failureThreshold` option defines how many times the probe should fail before the state should be changed from ready to not ready. By default this value is set to 3 if you do not set it.

The liveness probe is similar, but instead of changing states the liveness probe simply kills the pod if the failure threshold is exceeded. This is useful because there may be something wrong causing the pod not to behave correctly and spinning up a new instance could be the solution.

== Deploy name and ping microservices

To build these microservices, navigate to the `start` directory and run the following command.

```
mvn package
```

When the build succeeds, run the following command to deploy the necessary {kube} resources to serve the applications.

```
kubectl apply -f kubernetes.yaml
```

// Observe that once ready it can accept requests

Use the following command to view the status of the pods.

```
kubectl get pods
```

[source, role="no_copy"]
----
NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-5f868854bf-2rhdq   1/1       Running   0          28s
name-deployment-5f868854bf-ckhlf   1/1       Running   0          28s
ping-deployment-649d5564f9-f7lh2   1/1       Running   0          28s
----

When the pods are in the ready state, navigate to `{name-api}` and observe a response similar to `Hello! I'm container name-deployment-6bd97d9bf6-qbhbc`. The readiness probe ensures that the status will not be updated until the container is available to accept requests. Without a readiness probe you may notice an unsuccessful response from the server. This is because the container has started, but Open Liberty may not have fully initialized. With the readiness probe it is guaranteed that the pod will only begin accepting traffic once the microservice has fully started.

Similarly, navigate to `{ping-api}/name-service` and observe a response with the content `pong`.

== Trigger restart in name microservice

An endpoint has been provided under the name microservice to "kill" it by setting an unhealthy state in the health check causing the readiness and liveness probe to fail. Invoke this endpoint by making a POST request to `{name-api}/kill`. Run the following command to view the state of the pods:

```
kubectl get pods
```

[source, role="no_copy"]
----

NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-5f868854bf-2rhdq   1/1       Running   0          1m
name-deployment-5f868854bf-ckhlf   0/1       Running   0          1m
ping-deployment-649d5564f9-f7lh2   1/1       Running   0          1m
----

[source, role="no_copy"]
----
NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-5f868854bf-2rhdq   1/1       Running   0          1m
name-deployment-5f868854bf-ckhlf   0/1       Running   1          1m
ping-deployment-649d5564f9-f7lh2   1/1       Running   0          1m
----

[source, role="no_copy"]
----
NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-5f868854bf-2rhdq   1/1       Running   0          1m
name-deployment-5f868854bf-ckhlf   1/1       Running   1          1m
ping-deployment-649d5564f9-f7lh2   1/1       Running   0          1m
----

You will notice that one of the two name pods is no longer in the ready state and it will shortly be restarted. Navigate to `{name-api}` to observe that due to having two replicas where one is still healthy, your request will still be successful.

== Trigger restart in name microservice and observe effects on ping microservice

Make two POST requests to `{name-api}/kill`. If you see the same pod name twice make the request again until you see that the second pod has been made unhealthy. This is because there is a delay between a pod becoming unhealthy and the readiness probe noticing. Therefore, traffic may still be routed to the unhealthy service for approximately five seconds. Continue to observe the output of `kubectl get pods`. You will see that both pods are no longer ready and will soon be restarted. During this process the readiness probe for the `ping` microservice will also fail and you will observe that it is no longer in the ready state either.

First, both name pods will be restarted because the readiness and liveness probes failed.

[source, role="no_copy"]
----
NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-5f868854bf-2rhdq   0/1       Running   1          4m
name-deployment-5f868854bf-ckhlf   0/1       Running   2          4m
ping-deployment-649d5564f9-f7lh2   1/1       Running   0          4m
----

Next, you will see the pods start to become ready again. You will also noticed that the ping pod is no longer ready, this is because the readiness probe failed since it could no longer reach the service `name-service`.

[source, role="no_copy"]
----
NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-5f868854bf-2rhdq   1/1       Running   1          4m
name-deployment-5f868854bf-ckhlf   0/1       Running   2          4m
ping-deployment-649d5564f9-f7lh2   0/1       Running   0          4m
----

Finally, you will see that all of the pods have recovered. Note that the ping pod is not restarted because it was not down long enough for the liveness probe's failure threshold to be exceeded.

[source, role="no_copy"]
----
NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-5f868854bf-2rhdq   1/1       Running   1          4m
name-deployment-5f868854bf-ckhlf   1/1       Running   2          4m
ping-deployment-649d5564f9-f7lh2   1/1       Running   0          4m
----

// ================================================================================================================================
// ================================================================================================================================

== Testing the microservices

Run the tests by running the following command and appropriately substituting `[hostname]` for the correct value.

```
mvn verify -Ddockerfile.skip=true -Dcluster.ip=[hostname]
```

The tests check that `name` responds with a container name, and they check that `ping` responds with `pong` on success and that it gracefully handles a bad response.

Once the tests succeed, you should see output similar to the following in your console.

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.name.NameEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.542 sec - in it.io.openliberty.guides.name.NameEndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.ping.PingEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.761 sec - in it.io.openliberty.guides.ping.PingEndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

== Tearing down the {kube} resources

To remove all of the resources created during this guide, run the following command to delete all of the resources that you created.

```
kubectl delete -f kubernetes.yaml
```

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have used MicroProfile Health to create an endpoint that reports on your microservice's current status. Then you observed how {kube} leverages the `/health` endpoint to keep your microservices running smoothly.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
