// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: kubernetes-microprofile-health
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2018-11-30
:page-description: Learn how to check the health of microservices on Kubernetes by setting up readiness and liveness probes to inspect MicroProfile Health Check endpoints.
:page-tags: ['Kubernetes', 'Docker', 'MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-health', 'kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Checking the health of microservices by using Kubernetes readiness and liveness probes
:page-seo-description: A tutorial and example on how to report health status of microservices using MicroProfile Health Check and check them with Kubernetes readiness and liveness probes
:guide-author: Open Liberty
= Checking the health of microservices on Kubernetes

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to check the health of microservices on Kubernetes by setting up readiness and liveness probes to inspect MicroProfile Health Check endpoints.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:system-api: http://[hostname]:31000/system
:inventory-api: http://[hostname]:32000/inventory/systems
:win: WINDOWS
:mac: MAC
:linux: LINUX

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to create health check endpoints for your microservices. Then, you 
will configure {kube} to use these endpoints to keep your microservices running smoothly.

MicroProfile Health allows services to report their health, and it publishes the overall 
health status to defined endpoints. If a service reports `UP`, then it's available. If 
the service reports `DOWN`, then it's unavailable. MicroProfile Health reports an individual 
service status at the endpoint and indicates the overall status as `UP` if all the services 
are `UP`. A service orchestrator can then use the health statuses to make decisions.

{kube} provides liveness and readiness probes that are used to check the health of your 
containers. These probes can check certain files in your containers, check a TCP socket, 
or make HTTP requests. MicroProfile Health exposes readiness and liveness endpoints on 
your microservices. {kube} polls these endpoints as specified by the probes to react 
appropriately to any change in the microservice's status. Read the 
https://openliberty.io/guides/microprofile-health.html[Adding health reports to microservices^] 
guide to learn more about MicroProfile Health.

The two microservices you will work with are called `system` and `inventory`. The `system` microservice
returns the JVM system properties of the running container and it returns the pod's name in the HTTP header
making replicas easy to distinguish from each other. The `inventory` microservice
adds the properties from the `system` microservice to the inventory. This demonstrates
how communication can be established between pods inside a cluster.

// =================================================================================================
// Prerequisites
// =================================================================================================

[role=command]
include::{common-includes}/kube-prereq.adoc[]


// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Starting/Preparing Cluster
// =================================================================================================

[role=command]
include::{common-includes}/kube-start.adoc[]

// ================================================================================================================================
// ================================================================================================================================

== Adding health checks to the inventory microservice

Navigate to `start` directory to begin.

The `inventory` microservice should be healthy only when `system` is available. To add this 
check to the `/health/ready` endpoint, you will create a class that is annotated with the
`@Readiness` annotation and implements the `HealthCheck` interface.

[role="code_command hotspot", subs="quotes"] 
---- 
#Create the `InventoryReadinessCheck` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryReadinessCheck.java`
---- 

InventoryReadinessCheck.java
[source, Java, linenums, role='code_column']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryReadinessCheck.java[tags=**;!copyright;]
----

This health check verifies that the `system` microservice is available at 
`\http://system-service:9080/`. The `system-service` host name is only accessible from 
inside the cluster, you can't access it yourself. If it's available, then it returns an 
`UP` status. Similarly, if it's unavailable then it returns a `DOWN` status. When the 
status is `DOWN`, the microservice is considered to be unhealthy.

[role="code_command hotspot file=1", subs="quotes"] 
---- 
#Create the `InventoryLivenessCheck` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/InventoryLivenessCheck.java`
---- 

InventoryLivenessCheck.java
[source, Java, linenums, role='code_column']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryLivenessCheck.java[tags=**;!copyright;]
----

This liveness check verifies that the heap memory usage is below 90% of the maximum memory.
If more than 90% of the maximum memory is used, a status of `DOWN` will be returned. 

The health checks for the `system` microservice were already been implemented. The `system`
microservice was set up to become unhealthy for 60 seconds when a specific endpoint is called. 
This endpoint has been provided for you to observe the results of an unhealthy pod and how 
{kube} reacts.

== Configuring readiness and liveness probes

You will configure {kube} readiness and liveness probes. Readiness probes are responsible for 
determining that your application is ready to accept requests. If it's not ready, traffic 
won't be routed to the container. Liveness probes are responsible for determining when a 
container needs to be restarted. 

[role="code_command hotspot", subs="quotes"] 
---- 
#Create the kubernetes configuration file.#
`kubernetes.yaml`
---- 

kubernetes.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/kubernetes.yaml[tags=**;]
----

The readiness and liveness probes are configured for the containers running the `system` 
and `inventory` microservices.

The readiness probes are configured to poll the [hotspot=25 hotspot=66]`/health/ready` endpoint. The readiness probe 
determines the READY status of the container as seen in the `kubectl get pods` output. The 
[hotspot=27 hotspot=68]`initialDelaySeconds` field defines how long the probe should wait before it 
starts to poll so the probe does not start making requests before the server has started. 
The [hotspot=30 hotspot=71]`failureThreshold` option defines how many times the probe should fail 
before the state should be changed from ready to not ready. The [hotspot=29 hotspot=70]`timeoutSeconds` 
option defines how many seconds before the probe times out. The [hotspot=28 hotspot=69]`periodSeconds` 
option defines how often the probe should poll the given endpoint.

The liveness probes are configured to poll the [hotspot=33 hotspot=74]`/health/live` endpoint. 
The liveness probes determine when a container needs to be restarted. Similar to the readiness
probes, the liveness probes also define [hotspot=35 hotspot=76]`initialDelaySeconds`, 
[hotspot=38 hotspot=79]`failureThreshold`, [hotspot=37 hotspot=78]`timeoutSeconds`,
and [hotspot=36 hotspot=77]`periodSeconds`.

== Deploying the microservices

To build these microservices, navigate to the `start` directory and run the following 
command.

[role=command]
```
mvn package
```

Next, run the `docker build` commands to build container images for your application:
[role='command']
```
docker build -t system:1.0-SNAPSHOT system/.
docker build -t inventory:1.0-SNAPSHOT inventory/.
```

The `-t` flag in the `docker build` command allows the Docker image to be labeled (tagged) in the `name[:tag]` format. 
The tag for an image describes the specific image version. If the optional `[:tag]` tag is not specified, the `latest` tag is created by default.

When the builds succeed, run the following command to deploy the necessary {kube} 
resources to serve the applications.

[role=command]
```
kubectl apply -f kubernetes.yaml
```

Use the following command to view the status of the pods. There will be two `system` pods 
and one `inventory` pod, later you'll observe their behavior as the `system` pods become unhealthy.

[role=command]
```
kubectl get pods
```

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-694c7b74f7-hcf4q     1/1       Running   0          59s
system-deployment-694c7b74f7-lrlf7     1/1       Running   0          59s
inventory-deployment-cf8f564c6-nctcr   1/1       Running   0          59s
----

Wait until the pods are ready. After the pods are ready, you will make requests to your 
services.

include::{common-includes}/os-tabs.adoc[]

[.tab_content.windows_section.mac_section]
--
The default host name for Docker Desktop is `localhost`.
--

[.tab_content.linux_section]
--
The default host name for minikube is {minikube-ip}. Otherwise it can be found using the 
`minikube ip` command.
--

Navigate to `{system-api}/properties` and observe a response
containing JVM system properties. Replace `[hostname]` with the 
IP address or host name of your {kube} cluster. The readiness probe ensures the READY 
state won't be `1/1` until the container is available to accept requests. Without a 
readiness probe, you may notice an unsuccessful response from the server. This scenario 
can occur when the container has started, but the application server hasn't fully 
initialized. With the readiness probe, you can be certain the pod will only accept 
traffic when the microservice has fully started.

Similarly, navigate to `{inventory-api}/system-service` and observe that the request is successful.

== Changing the ready state of the system microservice

An endpoint has been provided under the `system` microservice to set it to an unhealthy 
state in the health check. The unhealthy state will cause the readiness probe to fail. 
Use the `curl` command to invoke this endpoint by making a POST request to 
`{system-api}/unhealthy` -- if `curl` is unavailable then use a tool such as 
https://www.getpostman.com/[Postman^].

[subs="attributes", role=command]
```
curl -X POST {system-api}/unhealthy
```

Run the following command to view the state of the pods:

[role=command]
```
kubectl get pods
```

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-694c7b74f7-hcf4q     1/1       Running   0          1m
system-deployment-694c7b74f7-lrlf7     0/1       Running   0          1m
inventory-deployment-cf8f564c6-nctcr   1/1       Running   0          1m
----

You will notice that one of the two `system` pods is no longer in the ready state. Navigate 
to `{system-api}/properties`. Observe that your request will still be successful because you have two 
replicas and one is still healthy.

=== Observing the effects on the inventory microservice

Wait until the `system` pod is ready again. Make two POST requests to `{system-api}/unhealthy`.
 If you see the same pod name twice, make the request again until you see that the second 
 pod has been made unhealthy. You may see the same pod twice because there's a delay 
 between a pod becoming unhealthy and the readiness probe noticing it. Therefore, traffic 
 may still be routed to the unhealthy service for approximately 5 seconds. Continue to 
 observe the output of `kubectl get pods`. You will see both pods are no longer ready. 
 During this process, the readiness probe for the `inventory` microservice will also fail. 
 Observe it's no longer in the ready state either.

First, both `system` pods will no longer be ready because the readiness probe failed.

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-694c7b74f7-hcf4q     0/1       Running   0          5m
system-deployment-694c7b74f7-lrlf7     0/1       Running   0          5m
inventory-deployment-cf8f564c6-nctcr   1/1       Running   0          5m
----

Next, the `inventory` pod is no longer ready because the readiness probe failed. The probe 
failed because `system-service` is now unavailable.

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-694c7b74f7-hcf4q     0/1       Running   0          6m
system-deployment-694c7b74f7-lrlf7     0/1       Running   0          6m
inventory-deployment-cf8f564c6-nctcr   0/1       Running   0          6m
----

Then, the `system` pods will start to become healthy again after 60 seconds.

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-694c7b74f7-hcf4q     1/1       Running   0          7m
system-deployment-694c7b74f7-lrlf7     0/1       Running   0          7m
inventory-deployment-cf8f564c6-nctcr   0/1       Running   0          7m
----

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-694c7b74f7-hcf4q     1/1       Running   0          7m
system-deployment-694c7b74f7-lrlf7     1/1       Running   0          7m
inventory-deployment-cf8f564c6-nctcr   0/1       Running   0          7m
----

Finally, you will see all of the pods have recovered.

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-694c7b74f7-hcf4q     1/1       Running   0          8m
system-deployment-694c7b74f7-lrlf7     1/1       Running   0          8m
inventory-deployment-cf8f564c6-nctcr   1/1       Running   0          8m
----

// ================================================================================================================================
// ================================================================================================================================

== Testing the microservices

Run the tests by running the following command and appropriately substituting `[hostname]` 
for the correct value.

[role=command]
```
mvn failsafe:integration-test -Dcluster.ip=[hostname]
```

A few tests are included for you to test the basic functions of the microservices. If a test failure
occurs, then you might have introduced a bug into the code. To run the tests, wait for all pods to be
in the ready state before proceeding further.

When the tests succeed, you should see output similar to the following in your console.

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.65 s - in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.542 s - in it.io.openliberty.guides.inventory.InventoryEndpointIT

Results:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

== Tearing down the environment

To remove all of the resources created during this guide, run the following command to 
delete all of the resources that you created.

[role=command]
```
kubectl delete -f kubernetes.yaml
```

[role=command]
include::{common-includes}/kube-minikube-teardown.adoc[]


// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have used MicroProfile Health and Open Liberty to create endpoints that report on 
your microservice's status. Then, you observed how {kube} uses the `/health/ready` and
`/health/live` endpoints to keep your microservices running smoothly.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/attribution.adoc[subs="attributes"]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
